### ISSUE TITLE
need an email alert for when no incoming referrals have been received for 3 days

### ISSUE THREAD

**Issue by eric-jahn** [211tbc/synthesis#7]
This could indicate the sending system needs to be restarted.  This occurred on July 12, and it took many days before the error was caught, and the ServicePoint process was restarted.

**Comment by yd-adept** [comment]
Just an update on this.

In the __init__.py file, I added code to insert or update a record in a
table called last_date_time. This table stores the name of an event and a
date-time stamp.

There is a script called lastdatetime.py  located in
/home/synthesis/tbc-pyramid/synthesis/synthesis which queries the
last_date_time table and looks at the data-time stamp field to determine
how many days elapsed since that data-time stamp.

The problem I have is with the smtp server. The lastdatetime.py script is
unable to send and email using the credentials in the settings.py file. I
checked an older version of the settings.py file in
/home/synthesis/tbc-pyramid.old and the smtp values are the same. the last
time that file was edited was on August 15 2016.

Setting the smtp debug level to True shows the following:

send: 'ehlo milhouse.penguix.net\r\n'
reply: '250-server2.zagweb.net Hello milhouse.penguix.net
[173.241.204.12]\r\n'
reply: '250-SIZE 52428800\r\n'
reply: '250-8BITMIME\r\n'
reply: '250-PIPELINING\r\n'
reply: '250-AUTH PLAIN LOGIN\r\n'
reply: '250-XXXXXXXA\r\n'
reply: '250 XXXB\r\n'
reply: retcode (250); Msg: server2.zagweb.net Hello milhouse.penguix.net
[173.241.204.12]
SIZE 52428800
8BITMIME
PIPELINING
AUTH PLAIN LOGIN
XXXXXXXA
XXXB
send: 'AUTH PLAIN AHN5bnRoZXNpcwBwNG5ndTF4\r\n'
reply: '535 Incorrect authentication data\r\n'
reply: retcode (535); Msg: Incorrect authentication data
Traceback (most recent call last):
  File "lastdatetime.py", line 40, in <module>
    server.login(settings.SMTPUSERNAME, settings.SMTPSENDERPWD)
  File "/usr/lib/python2.7/smtplib.py", line 622, in login
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, 'Incorrect authentication data')

I can get the lastdatetime.py to work with gmail. Do you have any insight
on the smtp server currently in use by synthesis? Is there and alternative
smpt server that I can work with. My plan is to have lastdatetime.py run as
a cron job and it will be responsible for sending you your email alert.

**Comment by eric-jahn** [comment]
closed with https://github.com/211tbc/synthesis/commit/bb82526df20f21cb604b0bc81ee760735a1063ff
